### ISSUE TITLE
Missing project folder structure and file names

### ISSUE THREAD

**Issue by David-Berumen** [datafold/datafold-vscode-extension#3]
**Describe the bug**
When exploring the "Models to diff:" view, all of the .sql files are showing without a folder structure and no name, you can see the whole path and file name if you hover over each record. 
- Data diffing does not work from this view because it sends "sql" as model name (it works using the data-diff command and typing the model name)
> 2023-08-02 10:58:22.028 [debug] 10:58:22 ERROR    No dbt models found for `--select sql`        __main__.py
- Cannot search files due to file name not being shown.

**To Reproduce**
Not Applicable

**Expected behavior**
View each file name and their folder structure.

**Screenshots**
<img width="210" alt="image" src="https://github.com/datafold/datafold-vscode-extension/assets/73449775/99cf07a7-a6fc-4ff8-9fac-053c58f1a22b">

**Logs**
> Refreshing model list:
> 2023-08-02 10:40:40.255 [debug] {"targetPath":"target","manifestJsonPath":"C:\\..\\..\\target\\manifest.json"}
> 2023-08-02 10:40:40.255 [info] Refreshing models list
> 2023-08-02 10:40:40.257 [debug] Getting children for undefined
> 2023-08-02 10:40:40.258 [debug] Children for undefined: _list of paths for each file_
> 2023-08-02 10:40:40.258 [debug] Getting tree item _one tree item for file_

**Environment (please complete the following information):**
- OS: Windows 11
- Python interpreter version: 3.10.11
- VSCode version: 1.80.2
- dbt Core version: tried with dbt-snowflake 1.4.1, 1.5.2 and 1.6.0
- data-diff version: 0.8.1
- Extension version: 0.0.24

**Extension settings screenshot**
<img width="625" alt="image" src="https://github.com/datafold/datafold-vscode-extension/assets/73449775/74b67a56-7de6-4005-a9e6-49c033962fb6">

**Additional context**
I tested with a .sql file on the first level of the "models" folder but it also did not show the name or path of the file. Also I cleaned and rebuilt the manifest.json file several times.

**Comment by sklinov** [comment]
@David-Berumen Thanks for reporting this.
Is it possible to show an example of a model from your `manifest.json` -> `nodes`?
`path` and `original_file_path` are of interest.

And `model-paths` in your `dbt_project.yml` is just `["models"]`?

**Comment by David-Berumen** [comment]
@sklinov sure, 

models path: 
`model-paths: ["models"]` 

<details>
  <summary> Example model</summary>
  
```json
    "model.Data_Mart.test": {
      "database": "db",
      "schema": "dbt",
      "name": "test",
      "resource_type": "model",
      "package_name": "Data_Mart",
      "path": "test.sql",
      "original_file_path": "models\\test.sql",
      "unique_id": "model.Data_Mart.test",
      "fqn": [
        "Data_Mart",
        "test"
      ],
      "alias": "test",
      "checksum": {
        "name": "sha256",
        "checksum": "..."
      },
      "config": {
        "enabled": true,
        "alias": null,
        "schema": null,
        "database": null,
        "tags": [],
        "meta": {},
        "group": null,
        "materialized": "view",
        "incremental_strategy": null,
        "persist_docs": {},
        "quoting": {},
        "column_types": {},
        "full_refresh": null,
        "unique_key": null,
        "on_schema_change": "ignore",
        "on_configuration_change": "apply",
        "grants": {},
        "packages": [],
        "docs": {
          "show": true,
          "node_color": null
        },
        "contract": {
          "enforced": false
        },
        "post-hook": [],
        "pre-hook": []
      },
      "tags": [],
      "description": "",
      "columns": {},
      "meta": {},
      "group": null,
      "docs": {
        "show": true,
        "node_color": null
      },
      "patch_path": null,
      "build_path": null,
      "deferred": false,
      "unrendered_config": {},
      "created_at": 1691084862.874448,
      "relation_name": "db.dbt.test",
      "raw_code": "select 1 from dual",
      "language": "sql",
      "refs": [],
      "sources": [],
      "metrics": [],
      "depends_on": {
        "macros": [],
        "nodes": []
      },
      "compiled_path": null,
      "contract": {
        "enforced": false,
        "checksum": null
      },
      "access": "protected",
      "constraints": [],
      "version": null,
      "latest_version": null,
      "deprecation_date": null
    }
```

</details>

**Comment by sklinov** [comment]
@David-Berumen Awesome, thanks!
[Version `0.0.25`](https://marketplace.visualstudio.com/items?itemName=Datafold.datafold-vscode) with the fix is out.
Please, check if it and give us feedback if it works for you

**Comment by David-Berumen** [comment]
Thank you @sklinov, It got better, I can see many files in their correct folder but there are some that are not showing or are showing in the wrong folder.

I think I have identified the issue, all of them are inside sub-folders with the same name that are located in different folders (they all are "base" models).

It ends up showing all the files on those same folders in just one folder with that name but if that specific folder is at a lower depth is does not show any of the files, here is an example of the two scenarios:

### 1.- Files in folders with same name at the same depth level are kept in a single folder (first valid path at that depth level)

 These 2 models end up in the same `<folder_with_same_name>` inside `folder_A_lvl2`:

- `models\folder_A_lvl1\folder_A_lvl2\<folder_with_same_name>\model_A.sql`
- `models\folder_B_lvl1\folder_B_lvl2\<folder_with_same_name>\model_B.sql`

### 2.- Files in folders with the same name at a lower depth level are not shown.

This file will not be shown because parent path folder is at a lower depth:

- `models\folder_C_lvl1\folder_C_lvl2\folder_C_lvl3\<folder_with_same_name>\model_C.sql`

Let me know if you have any question

**Comment by sklinov** [comment]
@David-Berumen Thanks for the feedback - I'll try to reproduce and make a fix for this

**Comment by sklinov** [comment]
@David-Berumen 0.0.26 is out with the fix of the described issue with folder structure.

**Comment by David-Berumen** [comment]
Thank you!, all folders and files look alright, will close issue 👍
